# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170727_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_column_compartment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_detector_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_detector_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_detector_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_pump',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_sampler_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_sampler_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='ip_address_2',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('LC', 'LC'), ('LCMS', 'LCMS'), ('GC', 'GC'), ('GCMS', 'GCMS')], default='LC', max_length=50),
        ),
    ]
