# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 21:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171128_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='ownership_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 5, 21, 52, 53, 268038, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
